services:
  - type: web
    name: byte-reality
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --bind 0.0.0.0:$PORT --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
